<?php

namespace Proxies\__CG__\AsesoresSABundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usuarios extends \AsesoresSABundle\Entity\Usuarios implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AsesoresSABundle\\Entity\\Usuarios' . "\0" . 'idusuario', '' . "\0" . 'AsesoresSABundle\\Entity\\Usuarios' . "\0" . 'contrasenausuario', '' . "\0" . 'AsesoresSABundle\\Entity\\Usuarios' . "\0" . 'nombreusuario', '' . "\0" . 'AsesoresSABundle\\Entity\\Usuarios' . "\0" . 'idperfil');
        }

        return array('__isInitialized__', '' . "\0" . 'AsesoresSABundle\\Entity\\Usuarios' . "\0" . 'idusuario', '' . "\0" . 'AsesoresSABundle\\Entity\\Usuarios' . "\0" . 'contrasenausuario', '' . "\0" . 'AsesoresSABundle\\Entity\\Usuarios' . "\0" . 'nombreusuario', '' . "\0" . 'AsesoresSABundle\\Entity\\Usuarios' . "\0" . 'idperfil');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Usuarios $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdusuario()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdusuario();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdusuario', array());

        return parent::getIdusuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setContrasenausuario($contrasenausuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContrasenausuario', array($contrasenausuario));

        return parent::setContrasenausuario($contrasenausuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getContrasenausuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContrasenausuario', array());

        return parent::getContrasenausuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreusuario($nombreusuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreusuario', array($nombreusuario));

        return parent::setNombreusuario($nombreusuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreusuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreusuario', array());

        return parent::getNombreusuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdperfil(\AsesoresSABundle\Entity\Perfil $idperfil = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdperfil', array($idperfil));

        return parent::setIdperfil($idperfil);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdperfil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdperfil', array());

        return parent::getIdperfil();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', array());

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', array());

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', array());

        return parent::eraseCredentials();
    }

}
