<?php

namespace Proxies\__CG__\AsesoresSABundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ramo extends \AsesoresSABundle\Entity\Ramo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AsesoresSABundle\\Entity\\Ramo' . "\0" . 'idramo', '' . "\0" . 'AsesoresSABundle\\Entity\\Ramo' . "\0" . 'siglaramo', '' . "\0" . 'AsesoresSABundle\\Entity\\Ramo' . "\0" . 'nombreramo', '' . "\0" . 'AsesoresSABundle\\Entity\\Ramo' . "\0" . 'tiporamo', '' . "\0" . 'AsesoresSABundle\\Entity\\Ramo' . "\0" . 'estadoramo');
        }

        return array('__isInitialized__', '' . "\0" . 'AsesoresSABundle\\Entity\\Ramo' . "\0" . 'idramo', '' . "\0" . 'AsesoresSABundle\\Entity\\Ramo' . "\0" . 'siglaramo', '' . "\0" . 'AsesoresSABundle\\Entity\\Ramo' . "\0" . 'nombreramo', '' . "\0" . 'AsesoresSABundle\\Entity\\Ramo' . "\0" . 'tiporamo', '' . "\0" . 'AsesoresSABundle\\Entity\\Ramo' . "\0" . 'estadoramo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Ramo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdramo()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdramo();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdramo', array());

        return parent::getIdramo();
    }

    /**
     * {@inheritDoc}
     */
    public function setSiglaramo($siglaramo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSiglaramo', array($siglaramo));

        return parent::setSiglaramo($siglaramo);
    }

    /**
     * {@inheritDoc}
     */
    public function getSiglaramo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSiglaramo', array());

        return parent::getSiglaramo();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreramo($nombreramo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreramo', array($nombreramo));

        return parent::setNombreramo($nombreramo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreramo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreramo', array());

        return parent::getNombreramo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTiporamo($tiporamo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTiporamo', array($tiporamo));

        return parent::setTiporamo($tiporamo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTiporamo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTiporamo', array());

        return parent::getTiporamo();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadoramo($estadoramo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadoramo', array($estadoramo));

        return parent::setEstadoramo($estadoramo);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadoramo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadoramo', array());

        return parent::getEstadoramo();
    }

}
