<?php

namespace Proxies\__CG__\AsesoresSABundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Anexo extends \AsesoresSABundle\Entity\Anexo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AsesoresSABundle\\Entity\\Anexo' . "\0" . 'idanexo', '' . "\0" . 'AsesoresSABundle\\Entity\\Anexo' . "\0" . 'numeroanexo', '' . "\0" . 'AsesoresSABundle\\Entity\\Anexo' . "\0" . 'iniciovigenciaanexo', '' . "\0" . 'AsesoresSABundle\\Entity\\Anexo' . "\0" . 'finvigenciaanexo', '' . "\0" . 'AsesoresSABundle\\Entity\\Anexo' . "\0" . 'valortotalaseguradoanexo', '' . "\0" . 'AsesoresSABundle\\Entity\\Anexo' . "\0" . 'idpago', '' . "\0" . 'AsesoresSABundle\\Entity\\Anexo' . "\0" . 'idramo', '' . "\0" . 'AsesoresSABundle\\Entity\\Anexo' . "\0" . 'idpoliza');
        }

        return array('__isInitialized__', '' . "\0" . 'AsesoresSABundle\\Entity\\Anexo' . "\0" . 'idanexo', '' . "\0" . 'AsesoresSABundle\\Entity\\Anexo' . "\0" . 'numeroanexo', '' . "\0" . 'AsesoresSABundle\\Entity\\Anexo' . "\0" . 'iniciovigenciaanexo', '' . "\0" . 'AsesoresSABundle\\Entity\\Anexo' . "\0" . 'finvigenciaanexo', '' . "\0" . 'AsesoresSABundle\\Entity\\Anexo' . "\0" . 'valortotalaseguradoanexo', '' . "\0" . 'AsesoresSABundle\\Entity\\Anexo' . "\0" . 'idpago', '' . "\0" . 'AsesoresSABundle\\Entity\\Anexo' . "\0" . 'idramo', '' . "\0" . 'AsesoresSABundle\\Entity\\Anexo' . "\0" . 'idpoliza');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Anexo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdanexo()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdanexo();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdanexo', array());

        return parent::getIdanexo();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroanexo($numeroanexo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroanexo', array($numeroanexo));

        return parent::setNumeroanexo($numeroanexo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroanexo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroanexo', array());

        return parent::getNumeroanexo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIniciovigenciaanexo($iniciovigenciaanexo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIniciovigenciaanexo', array($iniciovigenciaanexo));

        return parent::setIniciovigenciaanexo($iniciovigenciaanexo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIniciovigenciaanexo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIniciovigenciaanexo', array());

        return parent::getIniciovigenciaanexo();
    }

    /**
     * {@inheritDoc}
     */
    public function setFinvigenciaanexo($finvigenciaanexo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFinvigenciaanexo', array($finvigenciaanexo));

        return parent::setFinvigenciaanexo($finvigenciaanexo);
    }

    /**
     * {@inheritDoc}
     */
    public function getFinvigenciaanexo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFinvigenciaanexo', array());

        return parent::getFinvigenciaanexo();
    }

    /**
     * {@inheritDoc}
     */
    public function setValortotalaseguradoanexo($valortotalaseguradoanexo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValortotalaseguradoanexo', array($valortotalaseguradoanexo));

        return parent::setValortotalaseguradoanexo($valortotalaseguradoanexo);
    }

    /**
     * {@inheritDoc}
     */
    public function getValortotalaseguradoanexo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValortotalaseguradoanexo', array());

        return parent::getValortotalaseguradoanexo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdpago(\AsesoresSABundle\Entity\Pago $idpago = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdpago', array($idpago));

        return parent::setIdpago($idpago);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdpago()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdpago', array());

        return parent::getIdpago();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdramo(\AsesoresSABundle\Entity\Ramo $idramo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdramo', array($idramo));

        return parent::setIdramo($idramo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdramo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdramo', array());

        return parent::getIdramo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdpoliza(\AsesoresSABundle\Entity\Poliza $idpoliza = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdpoliza', array($idpoliza));

        return parent::setIdpoliza($idpoliza);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdpoliza()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdpoliza', array());

        return parent::getIdpoliza();
    }

}
